/**
 * @vitest-environment jsdom
 *
 * Environment is pinned per-file, matching the convention the rest of the suite
 * uses.
 *
 * Covers Task 00057: the shared responsive <img>. The fixtures below are copied
 * from what the three build scripts actually emit rather than invented, because
 * the whole point of this component is that all three rendition sources reach it
 * through one prop surface — a fixture that drifts from a manifest would prove
 * the component works against a shape no consumer ever passes it.
 */

import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';

import ResponsiveImage, { buildSrcSet } from './ResponsiveImage';

/**
 * One item exactly as `processOne` returns it in scripts/build-gallery.mjs.
 * `original` is the 1600w display webp despite the name; `full` is the untouched
 * source, several MB, and belongs behind a download link rather than in an
 * <img>. Only two rendition widths exist per gallery frame.
 */
const GALLERY_ITEM = {
    original: '/gallery/nc-eastcoast15/display/20150704_141233.jpg.webp',
    thumbnail: '/gallery/nc-eastcoast15/thumbs/20150704_141233.jpg.webp',
    full: '/gallery/nc-eastcoast15/original/20150704_141233.jpg',
    alt: 'NC East Coast Trip 2015 — 07/04/2015 14:12',
    thumbnailAlt: 'NC East Coast Trip 2015 — 07/04/2015 14:12',
    label: 'NC East Coast Trip 2015 — 07/04/2015 14:12',
    description: 'NC East Coast Trip 2015 photo taken 07/04/2015 14:12',
    loading: 'lazy',
    originalAlt: 'NC East Coast Trip 2015',
    _thumbId: 'nc-eastcoast15/20150704_141233.jpg',
};

const GALLERY_THUMB_W = 320;
const GALLERY_DISPLAY_W = 1600;

/** The adaptation each gallery consumer writes at its own call site. */
const galleryCandidates = (item) => [
    { width: GALLERY_THUMB_W, url: item.thumbnail },
    { width: GALLERY_DISPLAY_W, url: item.original },
];

/**
 * Two entries from public/hero/manifest.json, generated by
 * scripts/build-heroes.mjs. `nc` is the load-bearing one: its source photo is
 * 800px wide, so its ladder has two rungs where `na` has three. Nothing may
 * assume a fixed rung count.
 */
const HERO_NC = {
    key: 'nc',
    widest: '/hero/nc-800.webp',
    srcSet: '/hero/nc-480.webp 480w, /hero/nc-800.webp 800w',
};

const HERO_NA = {
    key: 'na',
    widest: '/hero/na-1024.webp',
    srcSet: '/hero/na-480.webp 480w, /hero/na-960.webp 960w, /hero/na-1024.webp 1024w',
};

/**
 * scripts/build-article-images.mjs emits no manifest at all — just files at
 * /articles/<id>/<slug>-<w>.webp, with rungs wider than the source dropped. A
 * consumer therefore truncates the ladder itself, as GoodbyeC8.jsx already does
 * against its recorded intrinsic widths.
 */
const ARTICLE_WIDTHS = [640, 960, 1280, 1600];

const articleCandidates = (slug, sourceWidth) =>
    ARTICLE_WIDTHS.filter((width) => width <= sourceWidth).map((width) => ({
        width,
        url: `/articles/goodbye-c8/${slug}-${width}.webp`,
    }));

const imageOf = (container) => container.querySelector('img');

/**
 * The contract violations throw during render, which React reports through
 * console.error before rethrowing. Silencing it keeps a passing run's output
 * readable.
 */
const expectRenderToThrow = (element, message) => {
    const quiet = vi.spyOn(console, 'error').mockImplementation(() => {});

    try {
        expect(() => render(element)).toThrow(message);
    } finally {
        quiet.mockRestore();
    }
};

afterEach(cleanup);

describe('buildSrcSet assembles a candidate list', () => {
    it('pairs each url with its width descriptor', () => {
        expect(buildSrcSet(galleryCandidates(GALLERY_ITEM))).toBe(
            `${GALLERY_ITEM.thumbnail} 320w, ${GALLERY_ITEM.original} 1600w`
        );
    });

    it('truncates nothing on its own — the caller owns which rungs exist', () => {
        expect(buildSrcSet(articleCandidates('1726961254977', 1080))).toBe(
            '/articles/goodbye-c8/1726961254977-640.webp 640w, /articles/goodbye-c8/1726961254977-960.webp 960w'
        );
    });

    it('passes a pre-built string through untouched', () => {
        expect(buildSrcSet(HERO_NC.srcSet)).toBe(HERO_NC.srcSet);
    });

    it('resolves an absent or empty candidate list to undefined, never an empty string', () => {
        expect(buildSrcSet(undefined)).toBeUndefined();
        expect(buildSrcSet([])).toBeUndefined();
        expect(buildSrcSet('')).toBeUndefined();
    });
});

describe('gallery-manifest-shaped data reaches the img', () => {
    it('advertises both rendition widths', () => {
        const { container } = render(
            <ResponsiveImage
                src={GALLERY_ITEM.original}
                srcSet={galleryCandidates(GALLERY_ITEM)}
                sizes="(max-width: 900px) 100vw, 900px"
                alt={GALLERY_ITEM.alt}
            />
        );

        expect(imageOf(container).getAttribute('srcset')).toBe(
            `${GALLERY_ITEM.thumbnail} 320w, ${GALLERY_ITEM.original} 1600w`
        );
    });

    it('never advertises the untouched original, which is a multi-megabyte file', () => {
        const { container } = render(
            <ResponsiveImage
                src={GALLERY_ITEM.original}
                srcSet={galleryCandidates(GALLERY_ITEM)}
                sizes="100vw"
                alt={GALLERY_ITEM.alt}
            />
        );

        const img = imageOf(container);

        expect(img.getAttribute('srcset')).not.toContain(GALLERY_ITEM.full);
        expect(img.getAttribute('src')).not.toBe(GALLERY_ITEM.full);
    });
});

describe('hero-manifest-shaped data reaches the img', () => {
    it('emits the pre-built candidate string verbatim', () => {
        const { container } = render(
            <ResponsiveImage
                src={HERO_NA.widest}
                srcSet={HERO_NA.srcSet}
                sizes="100vw"
                alt="The NA at night"
                loading="eager"
            />
        );

        expect(imageOf(container).getAttribute('srcset')).toBe(HERO_NA.srcSet);
    });

    it('carries a two-rung ladder as faithfully as a three-rung one', () => {
        const { container } = render(
            <ResponsiveImage
                src={HERO_NC.widest}
                srcSet={HERO_NC.srcSet}
                sizes="100vw"
                alt="The NC"
                loading="eager"
            />
        );

        expect(imageOf(container).getAttribute('srcset')).toBe(HERO_NC.srcSet);
    });
});

describe('sizes describes the layout box', () => {
    it('passes the caller value through', () => {
        const { container } = render(
            <ResponsiveImage
                src={GALLERY_ITEM.original}
                srcSet={galleryCandidates(GALLERY_ITEM)}
                sizes="(max-width: 760px) 100vw, 760px"
                alt={GALLERY_ITEM.alt}
            />
        );

        expect(imageOf(container).getAttribute('sizes')).toBe('(max-width: 760px) 100vw, 760px');
    });

    it('is omitted along with srcset when there are no candidates', () => {
        const { container } = render(<ResponsiveImage src="/images/na/one.jpg" alt="The NA" />);
        const img = imageOf(container);

        expect(img.hasAttribute('srcset')).toBe(false);
        expect(img.hasAttribute('sizes')).toBe(false);
    });

    it('refuses to render candidates without it, since the browser would assume 100vw', () => {
        expectRenderToThrow(
            <ResponsiveImage src={HERO_NA.widest} srcSet={HERO_NA.srcSet} alt="The NA at night" />,
            /`sizes` is required/
        );
    });
});

describe('loading defers by default', () => {
    it('lazy-loads when the caller says nothing', () => {
        const { container } = render(<ResponsiveImage src={GALLERY_ITEM.original} alt="A frame" />);

        expect(imageOf(container).getAttribute('loading')).toBe('lazy');
    });

    it('honours an eager opt-out for above-the-fold images', () => {
        const { container } = render(
            <ResponsiveImage src={HERO_NA.widest} alt="The NA at night" loading="eager" />
        );

        expect(imageOf(container).getAttribute('loading')).toBe('eager');
    });
});

describe('alt text is not optional', () => {
    it('throws loudly when a caller omits it', () => {
        expectRenderToThrow(
            <ResponsiveImage src={GALLERY_ITEM.original} />,
            /`alt` is required/
        );
    });

    it('accepts an empty string, which deliberately marks a decorative image', () => {
        const { container } = render(<ResponsiveImage src="/hero/flag.webp" alt="" />);
        const img = imageOf(container);

        expect(img.hasAttribute('alt')).toBe(true);
        expect(img.getAttribute('alt')).toBe('');
    });

    it('exposes real alt text to the accessibility tree', () => {
        render(<ResponsiveImage src={GALLERY_ITEM.original} alt={GALLERY_ITEM.alt} />);

        expect(screen.getByAltText(GALLERY_ITEM.alt)).toBeDefined();
    });
});

describe('remaining attributes ride through to the img', () => {
    it('carries layout and priority hints the caller sets', () => {
        const { container } = render(
            <ResponsiveImage
                src={GALLERY_ITEM.original}
                srcSet={galleryCandidates(GALLERY_ITEM)}
                sizes="100vw"
                alt={GALLERY_ITEM.alt}
                className="post__media"
                width={1600}
                height={900}
                decoding="async"
            />
        );

        const img = imageOf(container);

        expect(img.getAttribute('class')).toBe('post__media');
        expect(img.getAttribute('width')).toBe('1600');
        expect(img.getAttribute('height')).toBe('900');
        expect(img.getAttribute('decoding')).toBe('async');
    });
});
